import { resolve } from "node:path";
import type { ComparisonSignal } from "./comparison.js";
import { agreement, defaultPlotSignals, pairedValues, pearson } from "./comparison.js";
import { rowsToCsv, writeText } from "./io.js";

export interface PlotFile {
  readonly path: string;
  readonly title: string;
  readonly kind: "sites-by-results" | "correlation" | "agreement" | "scatter" | "fubar-selection" | "fubar-rates";
  readonly companionPaths?: readonly string[];
}

const palette = ["#117a70", "#d36b52", "#4577a7", "#9a6bb5", "#b88628", "#538c4c", "#b24f7c", "#4a858f"];

function escapeXml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;");
}

function finiteExtent(values: readonly number[]): readonly [number, number] {
  let minimum = Number.POSITIVE_INFINITY;
  let maximum = Number.NEGATIVE_INFINITY;
  for (const value of values) if (Number.isFinite(value)) { minimum = Math.min(minimum, value); maximum = Math.max(maximum, value); }
  if (!Number.isFinite(minimum) || !Number.isFinite(maximum)) return [0, 1];
  if (minimum === maximum) return [minimum - Math.max(0.5, Math.abs(minimum) * 0.05), maximum + Math.max(0.5, Math.abs(maximum) * 0.05)];
  return [minimum, maximum];
}

function svgDocument(width: number, height: number, title: string, body: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">${escapeXml(title)}</title><desc id="desc">Generated by evo-cli from EvoOnline pipeline results.</desc>
  <style>text{font-family:Inter,Arial,sans-serif;fill:#29413b}.title{font-size:18px;font-weight:700}.subtitle{font-size:10px;fill:#667a74}.label{font-size:9px;font-weight:650}.tick{font-size:8px;fill:#71827d}.axis{stroke:#9fb1ab;stroke-width:1}.grid{stroke:#e3e9e6;stroke-width:1}.threshold{stroke:#b85243;stroke-width:1;stroke-dasharray:4 3}.cell{stroke:#fff;stroke-width:1}.value{font-size:8px;text-anchor:middle;dominant-baseline:middle}.point{fill-opacity:.58}.legend{font-size:9px}</style>
  <rect width="100%" height="100%" fill="#fff"/>${body}
</svg>
`;
}

function compact(value: string, length = 42): string {
  return value.length <= length ? value : `${value.slice(0, length - 1)}…`;
}

function routeLabel(signal: ComparisonSignal): string {
  return signal.methodId === "simulator" ? signal.methodLabel : `${signal.methodLabel} via ${signal.sourceLabel}`;
}

async function sitesByResults(directory: string, signalsInput: readonly ComparisonSignal[]): Promise<PlotFile | undefined> {
  const signals = defaultPlotSignals(signalsInput).slice(0, 18);
  if (signals.length === 0) return undefined;
  const sites = signals.flatMap((signal) => signal.values.map((value) => value.ordinal));
  const [minimumSite, maximumSite] = finiteExtent(sites);
  const width = 1160;
  const left = 245;
  const right = 70;
  const top = 58;
  const laneHeight = 92;
  const bottom = 42;
  const height = top + laneHeight * signals.length + bottom;
  const plotWidth = width - left - right;
  const x = (site: number): number => left + (site - minimumSite) / Math.max(1, maximumSite - minimumSite) * plotWidth;
  const lanes = signals.map((signal, index) => {
    const laneTop = top + index * laneHeight;
    const laneBottom = laneTop + laneHeight - 24;
    const [rawMinimum, rawMaximum] = finiteExtent([...signal.values.map((value) => value.value), signal.threshold]);
    const padding = (rawMaximum - rawMinimum) * 0.05;
    const minimum = rawMinimum - padding;
    const maximum = rawMaximum + padding;
    const y = (value: number): number => laneBottom - (value - minimum) / Math.max(Number.EPSILON, maximum - minimum) * (laneBottom - laneTop);
    const points = [...signal.values].sort((a, b) => a.ordinal - b.ordinal);
    const path = points.map((point, pointIndex) => `${pointIndex === 0 ? "M" : "L"}${x(point.ordinal).toFixed(2)},${y(point.value).toFixed(2)}`).join(" ");
    const color = palette[index % palette.length]!;
    return `<rect x="${left}" y="${laneTop}" width="${plotWidth}" height="${laneBottom - laneTop}" fill="${index % 2 === 0 ? "#f7faf8" : "#fbfcfb"}"/>
      <line class="grid" x1="${left}" y1="${y((minimum + maximum) / 2)}" x2="${width - right}" y2="${y((minimum + maximum) / 2)}"/>
      <line class="threshold" x1="${left}" y1="${y(signal.threshold)}" x2="${width - right}" y2="${y(signal.threshold)}"/>
      <path d="${path}" fill="none" stroke="${color}" stroke-width="1.8"/>
      <text class="label" x="18" y="${laneTop + 18}">${escapeXml(compact(`${signal.methodLabel} via ${signal.sourceLabel}`, 39))}</text>
      <text class="tick" x="18" y="${laneTop + 34}">${escapeXml(compact(signal.metricLabel, 45))}</text>
      <text class="tick" x="${left - 8}" y="${laneTop + 7}" text-anchor="end">${maximum.toPrecision(4)}</text>
      <text class="tick" x="${left - 8}" y="${laneBottom}" text-anchor="end">${minimum.toPrecision(4)}</text>
      <text class="tick" x="${width - right + 7}" y="${y(signal.threshold) + 3}">cut ${signal.threshold.toPrecision(4)}</text>`;
  }).join("\n");
  const ticks = [0, .25, .5, .75, 1].map((fraction) => {
    const site = minimumSite + fraction * (maximumSite - minimumSite);
    return `<line class="grid" x1="${x(site)}" y1="${top}" x2="${x(site)}" y2="${height - bottom}"/><text class="tick" x="${x(site)}" y="${height - 16}" text-anchor="middle">${Math.round(site)}</text>`;
  }).join("");
  const path = resolve(directory, "sites-by-results.svg");
  await writeText(path, svgDocument(width, height, "Sites by results", `<text class="title" x="18" y="28">Sites by results</text><text class="subtitle" x="18" y="44">One selected metric per method × tree-source route; each lane retains its own native scale and threshold.</text>${ticks}${lanes}<text class="label" x="${left + plotWidth / 2}" y="${height - 3}" text-anchor="middle">Codon site</text>`));
  return { path, title: "Sites by results", kind: "sites-by-results" };
}

function matrixColor(value: number | null, diverging: boolean): string {
  if (value === null) return "#eef2f0";
  if (!diverging) {
    const t = Math.max(0, Math.min(1, value));
    return `rgb(${Math.round(245 - 118 * t)},${Math.round(248 - 79 * t)},${Math.round(246 - 96 * t)})`;
  }
  const t = Math.max(-1, Math.min(1, value));
  return t >= 0
    ? `rgb(${Math.round(246 - 90 * t)},${Math.round(247 - 54 * t)},${Math.round(245 - 58 * t)})`
    : `rgb(${Math.round(246 + 8 * t)},${Math.round(247 + 85 * t)},${Math.round(245 + 28 * t)})`;
}

async function matrixPlot(directory: string, signalsInput: readonly ComparisonSignal[], mode: "correlation" | "agreement"): Promise<PlotFile | undefined> {
  const signals = defaultPlotSignals(signalsInput).slice(0, 14);
  if (signals.length < 2) return undefined;
  const labelWidth = 210;
  const cell = 58;
  const top = 160;
  const width = labelWidth + cell * signals.length + 22;
  const height = top + cell * signals.length + 22;
  const values = signals.flatMap((left, row) => signals.map((right, column) => {
    const value = mode === "correlation" ? pearson(pairedValues(left, right)) : agreement(left, right);
    const x = labelWidth + column * cell;
    const y = top + row * cell;
    const text = value === null ? "—" : mode === "agreement" ? `${Math.round(value * 100)}%` : value.toFixed(2);
    return `<rect class="cell" x="${x}" y="${y}" width="${cell}" height="${cell}" fill="${matrixColor(value, mode === "correlation")}"/><text class="value" x="${x + cell / 2}" y="${y + cell / 2}">${text}</text>`;
  })).join("");
  const labels = signals.map((signal, index) => `<text class="label" x="${labelWidth - 8}" y="${top + index * cell + cell / 2}" text-anchor="end" dominant-baseline="middle">${escapeXml(compact(routeLabel(signal), 31))}</text><text class="label" transform="translate(${labelWidth + index * cell + cell / 2} ${top - 8}) rotate(-55)" text-anchor="start">${escapeXml(compact(routeLabel(signal), 31))}</text>`).join("");
  const title = mode === "correlation" ? "Signal correlation matrix" : "Threshold agreement matrix";
  const path = resolve(directory, `${mode}-matrix.svg`);
  await writeText(path, svgDocument(width, height, title, `<text class="title" x="18" y="28">${title}</text><text class="subtitle" x="18" y="45">${mode === "correlation" ? "Pairwise-complete Pearson correlation on native metric scales." : "Jaccard agreement after applying one threshold and direction per method."}</text>${labels}${values}`));
  const csvRows = signals.flatMap((left) => signals.map((right) => {
    const pairs = pairedValues(left, right);
    const value = mode === "correlation" ? pearson(pairs) : agreement(left, right);
    return [left.id, left.methodLabel, left.sourceLabel, left.metricLabel, right.id, right.methodLabel, right.sourceLabel, right.metricLabel, pairs.length, value];
  }));
  const csvPath = resolve(directory, `${mode}-matrix.csv`);
  await writeText(csvPath, rowsToCsv(["left signal", "left method", "left source", "left metric", "right signal", "right method", "right source", "right metric", "shared observations", mode], csvRows));
  return { path, title, kind: mode, companionPaths: [csvPath] };
}

async function scatterPlot(directory: string, signalsInput: readonly ComparisonSignal[]): Promise<PlotFile | undefined> {
  const signals = defaultPlotSignals(signalsInput);
  if (signals.length < 2) return undefined;
  const leftSignal = signals[0]!;
  const rightSignal = signals[1]!;
  const pairs = pairedValues(leftSignal, rightSignal);
  if (pairs.length === 0) return undefined;
  const width = 760; const height = 610; const left = 92; const right = 28; const top = 62; const bottom = 78;
  const [minimumX, maximumX] = finiteExtent(pairs.map((pair) => pair[0]));
  const [minimumY, maximumY] = finiteExtent(pairs.map((pair) => pair[1]));
  const x = (value: number): number => left + (value - minimumX) / Math.max(Number.EPSILON, maximumX - minimumX) * (width - left - right);
  const y = (value: number): number => height - bottom - (value - minimumY) / Math.max(Number.EPSILON, maximumY - minimumY) * (height - top - bottom);
  const points = pairs.map(([a, b]) => `<circle class="point" cx="${x(a)}" cy="${y(b)}" r="3" fill="#117a70"/>`).join("");
  const correlation = pearson(pairs);
  const path = resolve(directory, "signal-scatter.svg");
  await writeText(path, svgDocument(width, height, "Cross-method signal scatter", `<text class="title" x="18" y="28">Cross-method signal scatter</text><text class="subtitle" x="18" y="45">n=${pairs.length} · Pearson r=${correlation === null ? "—" : correlation.toFixed(4)}</text><line class="axis" x1="${left}" y1="${height - bottom}" x2="${width - right}" y2="${height - bottom}"/><line class="axis" x1="${left}" y1="${top}" x2="${left}" y2="${height - bottom}"/>${points}<text class="label" x="${(left + width - right) / 2}" y="${height - 26}" text-anchor="middle">${escapeXml(compact(`${routeLabel(leftSignal)}: ${leftSignal.metricLabel}`, 88))}</text><text class="label" transform="translate(24 ${(top + height - bottom) / 2}) rotate(-90)" text-anchor="middle">${escapeXml(compact(`${routeLabel(rightSignal)}: ${rightSignal.metricLabel}`, 78))}</text><text class="tick" x="${left}" y="${height - bottom + 16}" text-anchor="middle">${minimumX.toPrecision(4)}</text><text class="tick" x="${width - right}" y="${height - bottom + 16}" text-anchor="middle">${maximumX.toPrecision(4)}</text><text class="tick" x="${left - 8}" y="${height - bottom}" text-anchor="end">${minimumY.toPrecision(4)}</text><text class="tick" x="${left - 8}" y="${top + 3}" text-anchor="end">${maximumY.toPrecision(4)}</text>`));
  return { path, title: "Cross-method signal scatter", kind: "scatter" };
}

async function fubarPlots(directory: string, signals: readonly ComparisonSignal[]): Promise<readonly PlotFile[]> {
  const records = new Map<string, ComparisonSignal[]>();
  for (const signal of signals.filter((candidate) => candidate.methodId === "fubar" && candidate.unit === "site")) {
    const key = signal.id.split(":site:")[0]!;
    records.set(key, [...(records.get(key) ?? []), signal]);
  }
  const output: PlotFile[] = [];
  let ordinal = 0;
  for (const candidates of records.values()) {
    ordinal += 1;
    const positive = candidates.find((signal) => signal.metricId === "pPositive");
    const purifying = candidates.find((signal) => signal.metricId === "pPurifying");
    const dn = candidates.find((signal) => signal.metricId === "posterior-mean-dn");
    const ds = candidates.find((signal) => signal.metricId === "posterior-mean-ds");
    const ratioSignal = candidates.find((signal) => signal.metricId === "exp-log-mean-rate-ratio");
    const prefix = records.size > 1 ? `fubar-${String(ordinal).padStart(2, "0")}` : "fubar";
    for (const [kind, selected, threshold, title] of [
      ["fubar-selection", [positive, purifying].filter((value): value is ComparisonSignal => value !== undefined), positive?.threshold ?? 0.95, "FUBAR site selection posterior"],
      ["fubar-rates", [dn, ds, ratioSignal].filter((value): value is ComparisonSignal => value !== undefined), 1, "FUBAR posterior rate profile"],
    ] as const) {
      if (selected.length === 0) continue;
      const sites = selected.flatMap((signal) => signal.values.map((value) => value.ordinal));
      const [minimumSite, maximumSite] = finiteExtent(sites);
      const allValues = selected.flatMap((signal) => signal.values.map((value) => value.value));
      const [rawMinimum, rawMaximum] = finiteExtent([...allValues, threshold]);
      const width = 1050; const height = 430; const left = 80; const right = 30; const top = 66; const bottom = 64;
      const x = (site: number): number => left + (site - minimumSite) / Math.max(1, maximumSite - minimumSite) * (width - left - right);
      const y = (value: number): number => height - bottom - (value - rawMinimum) / Math.max(Number.EPSILON, rawMaximum - rawMinimum) * (height - top - bottom);
      const series = selected.map((signal, index) => {
        const path = [...signal.values].sort((a, b) => a.ordinal - b.ordinal).map((value, point) => `${point === 0 ? "M" : "L"}${x(value.ordinal)},${y(value.value)}`).join(" ");
        return `<path d="${path}" fill="none" stroke="${palette[index]!}" stroke-width="2"/><line x1="${left + index * 190}" y1="42" x2="${left + index * 190 + 24}" y2="42" stroke="${palette[index]!}" stroke-width="3"/><text class="legend" x="${left + index * 190 + 30}" y="45">${escapeXml(compact(signal.metricLabel, 26))}</text>`;
      }).join("");
      const routeTitle = `${title} · ${candidates[0]!.sourceLabel}`;
      const path = resolve(directory, `${prefix}-${kind === "fubar-selection" ? "selection" : "rates"}.svg`);
      await writeText(path, svgDocument(width, height, routeTitle, `<text class="title" x="18" y="25">${escapeXml(routeTitle)}</text><line class="axis" x1="${left}" y1="${height - bottom}" x2="${width - right}" y2="${height - bottom}"/><line class="axis" x1="${left}" y1="${top}" x2="${left}" y2="${height - bottom}"/><line class="threshold" x1="${left}" y1="${y(threshold)}" x2="${width - right}" y2="${y(threshold)}"/>${series}<text class="label" x="${(left + width - right) / 2}" y="${height - 22}" text-anchor="middle">Codon site</text><text class="tick" x="${left - 8}" y="${y(rawMaximum) + 3}" text-anchor="end">${rawMaximum.toPrecision(4)}</text><text class="tick" x="${left - 8}" y="${y(rawMinimum) + 3}" text-anchor="end">${rawMinimum.toPrecision(4)}</text>`));
      output.push({ path, title: routeTitle, kind });
    }
  }
  return output;
}

export async function writeComparisonPlots(directory: string, signals: readonly ComparisonSignal[]): Promise<readonly PlotFile[]> {
  const plots = await Promise.all([
    sitesByResults(directory, signals),
    matrixPlot(directory, signals, "correlation"),
    matrixPlot(directory, signals, "agreement"),
    scatterPlot(directory, signals),
  ]);
  return [...plots.filter((plot): plot is PlotFile => plot !== undefined), ...await fubarPlots(directory, signals)];
}
