import type { JemsprAnalysisResult } from "@phylo-workbench/model-jemspr/browser-source";
import { JemsprGenomeFigure } from "./JemsprGenomeFigure.js";
import { JemsprLikelihoodTreeSequenceFigure } from "./JemsprLikelihoodTreeSequenceFigure.js";
import { JemsprNetworkDagFigure } from "./JemsprNetworkDagFigure.js";
import { JemsprTreeSequenceFigure } from "./JemsprTreeSequenceFigure.js";
import { JemsprDisplayGraphFigure, JemsprSprAnimationFigure, JemsprSprStoryboardFigure } from "./JemsprSprFigures.js";
import { RecombinationCodonHandoff, type RecombinationCodonMethod } from "./RecombinationCodonHandoff.js";
import { createJemsprCodonTreeSet } from "../lib/recombination-handoff.js";
import type { RecombinationCodonTreeSet } from "@phylo-workbench/model-diffubar/browser-source";
import { createJemsprRecombinationBundle, type EvoOnlineRecombinationTreeBundle } from "../lib/recombination-bundle.js";

function downloadText(text: string, filename: string, type = "text/plain;charset=utf-8"): void {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function JemsprResultsView({ result, onLoadRecombinationTrees }: { readonly result: JemsprAnalysisResult; readonly onLoadRecombinationTrees?: ((method: RecombinationCodonMethod, treeSet: RecombinationCodonTreeSet, bundle: EvoOnlineRecombinationTreeBundle) => void) | undefined }) {
  const elapsed = (result.timings.totalMs ?? 0) / 1000;
  const linked = result.likelihood.status === "complete" ? result.likelihood : undefined;
  const skippedReason = result.likelihood.status === "skipped" ? result.likelihood.reason : undefined;
  const masterTree = linked?.masterTree ?? result.network.masterTree;
  let codonTreeSet: RecombinationCodonTreeSet | undefined;
  let recombinationBundle: EvoOnlineRecombinationTreeBundle | undefined;
  let codonTreeError: string | undefined;
  try { codonTreeSet = createJemsprCodonTreeSet(result, result.sites); recombinationBundle = createJemsprRecombinationBundle(result, codonTreeSet); }
  catch (error) { codonTreeError = error instanceof Error ? error.message : String(error); }
  return <section className="results" aria-labelledby="jemspr-results-heading">
    <div className="section-heading section-heading--results"><div><p className="eyebrow">Analysis complete · coherent overlapping event network</p><h2 id="jemspr-results-heading">JEMSPR</h2><p>Joint latent-master, local-tree path, switching network, and coherent linked-length ML</p></div><div className="result-downloads"><button type="button" className="button button--primary" onClick={() => downloadText(result.eventsCsv, "jemspr-events.csv", "text/csv;charset=utf-8")}>Events CSV</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.localTreesTsv, "jemspr-local-trees.tsv")}>Local trees TSV</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.breakpointsTsv, "jemspr-breakpoints.tsv")}>Breakpoints TSV</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.networkJson, "jemspr-network.json", "application/json;charset=utf-8")}>Network JSON</button><button type="button" className="button button--secondary" onClick={() => downloadText(masterTree, "jemspr-master-linked-ml.nwk")}>ML master Newick</button><button type="button" className="button button--secondary" onClick={() => downloadText(JSON.stringify(result, null, 2), "jemspr-result.json", "application/json;charset=utf-8")}>Full result</button></div></div>
    <p className="method-note"><strong>What JEMSPR asks:</strong> which rooted latent master and persistent rSPR event templates form one coherent switching DAG whose overlapping active intervals explain the alignment? The master need not occur at any site, and event identity is retained across both endpoints.</p>
    <p className="method-note method-note--warning"><strong>Independence and search scope:</strong> topology, roots, SPR events, and breakpoint proposals are inferred internally—never supplied by FastTree, FSART, MosaicSPR, or an uploaded tree. When linked ML is enabled, FastTree is called once solely to estimate the fixed global GTR frequencies/exchangeabilities; every branch length, transition matrix, pruning pass, gradient, Gamma category, and genomic likelihood recursion is EvoOnline code.</p>
    <RecombinationCodonHandoff treeSet={codonTreeSet} bundle={recombinationBundle} error={codonTreeError} onLoad={onLoadRecombinationTrees} />
    {result.diagnostics.warnings.map((warning) => <p key={warning} className="method-note method-note--warning">{warning}</p>)}
    <div className="result-stats">
      <div><span>Latent master</span><strong>{result.network.masterStateId}</strong><small>{result.diagnostics.rootPlacements} inferred root starts</small></div>
      <div><span>Coherent regions</span><strong>{result.network.runs.length}</strong><small>{result.network.trees.length} occupied displays</small></div>
      <div><span>Event templates</span><strong>{result.network.templates.length}</strong><small>{result.network.occurrences.length} interval occurrences</small></div>
      <div><span>Maximum overlap</span><strong>{result.network.maximumOverlapUsed}</strong><small>cap {result.network.overlapCap}</small></div>
      <div><span>Temporal check</span><strong>{result.network.temporal.status}</strong><small>{result.network.boundaryConvention} boundaries</small></div>
      <div><span>Total time</span><strong>{elapsed < 10 ? elapsed.toFixed(2) : elapsed.toFixed(1)} s</strong><small>{result.diagnostics.graphStates} trees · {result.diagnostics.graphEdges} rSPR edges</small></div>
      {linked !== undefined && <div><span>Linked ML</span><strong>{linked.logLikelihood.toFixed(2)}</strong><small>{linked.atomicBranches.length} shared edges · {linked.runs.length} likelihood regions</small></div>}
    </div>

    {linked !== undefined ? <details className="result-panel" open><summary><span>Coherent linked branch-length likelihood</span><small>{`${linked.atomicBranches.length} atomic edges · ${linked.rateVariation.rates.length} rate categories · ${linked.refined ? "path refined" : "path retained"}`}</small></summary><div className="result-panel__body"><p className="method-note">{linked.certificate}</p><p className="figure-note">Fixed GTR frequencies A/C/G/T: {linked.model.frequencies.map((value) => value.toFixed(4)).join(" / ")} · exchangeabilities AC/AG/AT/CG/CT/GT: {linked.model.exchangeabilities.map((value) => value.toFixed(4)).join(" / ")} · custom Gamma shape {linked.rateVariation.shape.toFixed(3)}.</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Stage</th><th>Log likelihood</th><th>Iterations</th><th>Converged</th><th>Gradient RMS</th><th>Changed sites</th></tr></thead><tbody>{linked.rounds.map((round) => <tr key={`${round.round}-${round.phase}`}><td>{round.phase}</td><td>{round.logLikelihood.toFixed(3)}</td><td>{round.iterations}</td><td>{round.converged ? "yes" : "limit"}</td><td>{round.gradientRms.toExponential(3)}</td><td>{round.changedSites}</td></tr>)}</tbody></table></div><h3>Likelihood/Viterbi regions</h3><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Start</th><th>End</th><th>Mask</th><th>Length-fitted local tree</th></tr></thead><tbody>{linked.runs.map((run, index) => <tr key={`${run.start}-${run.end}-${run.mask}`}><td>{run.start}</td><td>{run.end}</td><td>{run.mask.toString(2).padStart(result.network.templates.length, "0")}</td><td><button type="button" className="button button--secondary" onClick={() => downloadText(run.tree, `jemspr-likelihood-region-${index + 1}.nwk`)}>Newick</button></td></tr>)}</tbody></table></div><h3>Shared atomic network edges</h3><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Edge</th><th>Network endpoints</th><th>Length</th><th>Used by masks</th></tr></thead><tbody>{linked.atomicBranches.map((branch) => <tr key={branch.id}><td>{branch.id}</td><td>{branch.parentNode} → {branch.childNode}</td><td>{branch.length.toPrecision(7)}</td><td>{branch.usedByMasks.join(", ")}</td></tr>)}</tbody></table></div>{linked.nonidentifiableGroups.length > 0 && <p className="method-note method-note--warning"><strong>Exact summed-length gauges:</strong> {linked.nonidentifiableGroups.map((group) => group.join(" + ")).join("; ")}. These edges have identical displayed-branch incidence and are not claimed as individually identified.</p>}</div></details> : <p className="method-note method-note--warning"><strong>Linked likelihood skipped:</strong> {skippedReason}</p>}

    <details className="result-panel" open><summary><span>Coherent genomic event history</span><small>{`${result.network.occurrences.length} occurrences · maximum overlap ${result.network.maximumOverlapUsed} · SVG`}</small></summary><div className="result-panel__body"><JemsprGenomeFigure result={result.network} sites={result.sites} /></div></details>
    {linked !== undefined && <details className="result-panel" open><summary><span>Likelihood-refined breakpoints and branch-length trees</span><small>Linked ML phylograms · shared substitutions/site scale · SVG</small></summary><div className="result-panel__body"><JemsprLikelihoodTreeSequenceFigure result={result.network} likelihood={linked} /></div></details>}
    <details className="result-panel" open><summary><span>Implied regional phylogenies</span><small>Select two for a tanglegram or all for linked trees · SVG</small></summary><div className="result-panel__body"><JemsprTreeSequenceFigure result={result.network} /></div></details>
    <details className="result-panel" open><summary><span>Compiled switching DAG</span><small>{`${result.network.templates.length} ordered reticulations · ${result.network.temporal.status} · SVG`}</small></summary><div className="result-panel__body"><JemsprNetworkDagFigure networkJson={result.networkJson} /><p className={`method-note${result.network.temporal.status === "rank-feasible" ? "" : " method-note--warning"}`}><strong>Temporal feasibility:</strong> {result.network.temporal.message}</p></div></details>
    <details className="result-panel" open><summary><span>Animated genomic SPR strip</span><small>Alignment-linked regions · looping master-to-local trees · native horizontal scroll</small></summary><div className="result-panel__body"><JemsprSprAnimationFigure result={result} /></div></details>
    <details className="result-panel" open><summary><span>SPR move storyboard</span><small>Exact before/after source contexts · SVG</small></summary><div className="result-panel__body"><JemsprSprStoryboardFigure result={result} /></div></details>
    <details className="result-panel" open><summary><span>SPR display-state graph</span><small>Exact masks connected by single event toggles · SVG</small></summary><div className="result-panel__body"><JemsprDisplayGraphFigure result={result} /></div></details>

    <details className="result-panel" open><summary><span>Event occurrences and templates</span><small>Persistent identities, endpoint ranges, and rSPR clades</small></summary><div className="result-panel__body"><p className="method-note">Endpoint ranges contain consecutive coordinates within {result.network.uncertaintyTolerance.toFixed(2)} optimization units of the selected directional opening/closure min-marginal; they are deterministic optimization ranges, not confidence intervals.</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Occurrence</th><th>Template</th><th>Interval</th><th>Censoring</th><th>Overlap</th><th>Endpoint gaps</th><th>Endpoint ranges</th><th>Pruned clade</th><th>Regraft destination</th></tr></thead><tbody>{result.network.occurrences.map((occurrence) => { const template = result.network.templates.find((candidate) => candidate.id === occurrence.templateId)!; return <tr key={occurrence.id}><td>{occurrence.id}</td><td>{occurrence.templateId}</td><td>{occurrence.start}–{occurrence.end}</td><td>{occurrence.leftCensored ? "left " : ""}{occurrence.rightCensored ? "right" : ""}{!occurrence.leftCensored && !occurrence.rightCensored ? "none" : ""}</td><td>{occurrence.maximumConcurrentEvents}</td><td>{occurrence.openingGap.toFixed(3)} / {occurrence.closingGap.toFixed(3)}</td><td>{`${occurrence.openingIntervalLow}–${occurrence.openingIntervalHigh} / ${occurrence.closingIntervalLow}–${occurrence.closingIntervalHigh}`}</td><td>{template.move.prunedTaxa.join(", ")}</td><td>{template.move.destinationIsRoot ? "above root" : template.move.destinationTaxa.join(", ")}</td></tr>; })}</tbody></table></div>{result.network.occurrences.length === 0 && <p className="figure-note">The selected penalized network retains no active event occurrences.</p>}</div></details>

    <details className="result-panel"><summary><span>Relaxed path and adaptive-tree audit</span><small>{`${result.path.runs.length} path regions · path objective ${result.path.objective.toFixed(3)}`}</small></summary><div className="result-panel__body"><p className="method-note">{result.path.certificate} The path and explicit-network layers use different regularizers, so their raw objective difference ({result.diagnostics.pathNetworkObjectiveDifference.toFixed(3)}) is descriptive, not a likelihood ratio or certified bound.</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Root start</th><th>Round</th><th>States</th><th>Edges</th><th>Occupied</th><th>Neighbours</th><th>Priced</th><th>Added</th><th>Objective</th><th>Best omitted gain</th><th>Master</th><th>Time</th></tr></thead><tbody>{result.path.iterations.map((iteration) => <tr key={`${iteration.start}-${iteration.iteration}`}><td>{iteration.start}</td><td>{iteration.iteration}</td><td>{iteration.graphStates}</td><td>{iteration.graphEdges}</td><td>{iteration.occupiedStates}</td><td>{iteration.neighboursEnumerated}</td><td>{iteration.neighboursPriced}</td><td>{iteration.statesAdded}</td><td>{iteration.objective.toFixed(3)}</td><td>{iteration.bestOmittedIntervalGain.toFixed(3)}</td><td>{iteration.masterStateId}</td><td>{(iteration.elapsedMs / 1000).toFixed(2)} s</td></tr>)}</tbody></table></div></div></details>

    <details className="result-panel"><summary><span>Network-search and regularization audit</span><small>Exact mask-DP scores plus hard temporal lazy cuts</small></summary><div className="result-panel__body"><p className="method-note">{result.network.certificate}</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Reticulations</th><th>Networks scored</th><th>Temporal rejects</th><th>Beam retained</th><th>Best objective</th><th>Data parsimony</th><th>Overlap</th><th>Time</th></tr></thead><tbody>{result.network.search.map((step) => <tr key={step.reticulations}><td>{step.reticulations}</td><td>{step.candidatesScored}</td><td>{step.temporallyRejected}</td><td>{step.beamRetained}</td><td>{step.bestObjective.toFixed(3)}</td><td>{step.bestDataParsimony.toFixed(3)}</td><td>{step.bestOverlap}</td><td>{(step.elapsedMs / 1000).toFixed(2)} s</td></tr>)}</tbody></table></div><h3>Nondominated retained solutions</h3><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Reticulations</th><th>Occurrences</th><th>Data parsimony</th><th>Penalized objective</th><th>Maximum overlap</th></tr></thead><tbody>{result.network.paretoFrontier.map((entry) => <tr key={`${entry.reticulations}-${entry.occurrences}`}><td>{entry.reticulations}</td><td>{entry.occurrences}</td><td>{entry.dataParsimony.toFixed(3)}</td><td>{entry.objective.toFixed(3)}</td><td>{entry.maximumOverlap}</td></tr>)}</tbody></table></div></div></details>
  </section>;
}
