import type { JemsprAnalysisResult } from "@phylo-workbench/model-jemspr/browser-source";
import { JemsprGenomeFigure } from "./JemsprGenomeFigure.js";
import { JemsprNetworkDagFigure } from "./JemsprNetworkDagFigure.js";
import { JemsprTreeSequenceFigure } from "./JemsprTreeSequenceFigure.js";

function downloadText(text: string, filename: string, type = "text/plain;charset=utf-8"): void {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function JemsprResultsView({ result }: { readonly result: JemsprAnalysisResult }) {
  const elapsed = (result.timings.totalMs ?? 0) / 1000;
  return <section className="results" aria-labelledby="jemspr-results-heading">
    <div className="section-heading section-heading--results"><div><p className="eyebrow">Analysis complete · coherent overlapping event network</p><h2 id="jemspr-results-heading">JEMSPR</h2><p>Joint latent-master, local-tree path, and rooted switching-network inference</p></div><div className="result-downloads"><button type="button" className="button button--primary" onClick={() => downloadText(result.eventsCsv, "jemspr-events.csv", "text/csv;charset=utf-8")}>Events CSV</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.localTreesTsv, "jemspr-local-trees.tsv")}>Local trees TSV</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.breakpointsTsv, "jemspr-breakpoints.tsv")}>Breakpoints TSV</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.networkJson, "jemspr-network.json", "application/json;charset=utf-8")}>Network JSON</button><button type="button" className="button button--secondary" onClick={() => downloadText(result.network.masterTree, "jemspr-master.nwk")}>Master Newick</button><button type="button" className="button button--secondary" onClick={() => downloadText(JSON.stringify(result, null, 2), "jemspr-result.json", "application/json;charset=utf-8")}>Full result</button></div></div>
    <p className="method-note"><strong>What JEMSPR asks:</strong> which rooted latent master and persistent rSPR event templates form one coherent switching DAG whose overlapping active intervals explain the alignment? The master need not occur at any site, and event identity is retained across both endpoints.</p>
    <p className="method-note method-note--warning"><strong>Independence and search scope:</strong> JEMSPR consumes the alignment directly. It does not call FastTree, FSART, MosaicSPR, an uploaded tree, or precomputed breakpoint proposals. Fixed graph/path and fixed network/mask inference are exact; adaptive rooted-tree expansion and the outer network beam are explicitly budgeted.</p>
    {result.diagnostics.warnings.map((warning) => <p key={warning} className="method-note method-note--warning">{warning}</p>)}
    <div className="result-stats">
      <div><span>Latent master</span><strong>{result.network.masterStateId}</strong><small>{result.diagnostics.rootPlacements} inferred root starts</small></div>
      <div><span>Coherent regions</span><strong>{result.network.runs.length}</strong><small>{result.network.trees.length} occupied displays</small></div>
      <div><span>Event templates</span><strong>{result.network.templates.length}</strong><small>{result.network.occurrences.length} interval occurrences</small></div>
      <div><span>Maximum overlap</span><strong>{result.network.maximumOverlapUsed}</strong><small>cap {result.network.overlapCap}</small></div>
      <div><span>Temporal check</span><strong>{result.network.temporal.status}</strong><small>{result.network.boundaryConvention} boundaries</small></div>
      <div><span>Total time</span><strong>{elapsed < 10 ? elapsed.toFixed(2) : elapsed.toFixed(1)} s</strong><small>{result.diagnostics.graphStates} trees · {result.diagnostics.graphEdges} rSPR edges</small></div>
    </div>

    <details className="result-panel" open><summary><span>Coherent genomic event history</span><small>{`${result.network.occurrences.length} occurrences · maximum overlap ${result.network.maximumOverlapUsed} · SVG`}</small></summary><div className="result-panel__body"><JemsprGenomeFigure result={result.network} sites={result.sites} /></div></details>
    <details className="result-panel" open><summary><span>Implied regional phylogenies</span><small>Select two for a tanglegram or all for linked trees · SVG</small></summary><div className="result-panel__body"><JemsprTreeSequenceFigure result={result.network} /></div></details>
    <details className="result-panel" open><summary><span>Compiled switching DAG</span><small>{`${result.network.templates.length} ordered reticulations · ${result.network.temporal.status} · SVG`}</small></summary><div className="result-panel__body"><JemsprNetworkDagFigure networkJson={result.networkJson} /><p className={`method-note${result.network.temporal.status === "rank-feasible" ? "" : " method-note--warning"}`}><strong>Temporal feasibility:</strong> {result.network.temporal.message}</p></div></details>

    <details className="result-panel" open><summary><span>Event occurrences and templates</span><small>Persistent identities, endpoint ranges, and rSPR clades</small></summary><div className="result-panel__body"><p className="method-note">Endpoint ranges contain consecutive coordinates within {result.network.uncertaintyTolerance.toFixed(2)} optimization units of the selected directional opening/closure min-marginal; they are deterministic optimization ranges, not confidence intervals.</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Occurrence</th><th>Template</th><th>Interval</th><th>Censoring</th><th>Overlap</th><th>Endpoint gaps</th><th>Endpoint ranges</th><th>Pruned clade</th><th>Regraft destination</th></tr></thead><tbody>{result.network.occurrences.map((occurrence) => { const template = result.network.templates.find((candidate) => candidate.id === occurrence.templateId)!; return <tr key={occurrence.id}><td>{occurrence.id}</td><td>{occurrence.templateId}</td><td>{occurrence.start}–{occurrence.end}</td><td>{occurrence.leftCensored ? "left " : ""}{occurrence.rightCensored ? "right" : ""}{!occurrence.leftCensored && !occurrence.rightCensored ? "none" : ""}</td><td>{occurrence.maximumConcurrentEvents}</td><td>{occurrence.openingGap.toFixed(3)} / {occurrence.closingGap.toFixed(3)}</td><td>{`${occurrence.openingIntervalLow}–${occurrence.openingIntervalHigh} / ${occurrence.closingIntervalLow}–${occurrence.closingIntervalHigh}`}</td><td>{template.move.prunedTaxa.join(", ")}</td><td>{template.move.destinationIsRoot ? "above root" : template.move.destinationTaxa.join(", ")}</td></tr>; })}</tbody></table></div>{result.network.occurrences.length === 0 && <p className="figure-note">The selected penalized network retains no active event occurrences.</p>}</div></details>

    <details className="result-panel"><summary><span>Relaxed path and adaptive-tree audit</span><small>{`${result.path.runs.length} path regions · path objective ${result.path.objective.toFixed(3)}`}</small></summary><div className="result-panel__body"><p className="method-note">{result.path.certificate} The path and explicit-network layers use different regularizers, so their raw objective difference ({result.diagnostics.pathNetworkObjectiveDifference.toFixed(3)}) is descriptive, not a likelihood ratio or certified bound.</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Root start</th><th>Round</th><th>States</th><th>Edges</th><th>Occupied</th><th>Neighbours</th><th>Priced</th><th>Added</th><th>Objective</th><th>Best omitted gain</th><th>Master</th><th>Time</th></tr></thead><tbody>{result.path.iterations.map((iteration) => <tr key={`${iteration.start}-${iteration.iteration}`}><td>{iteration.start}</td><td>{iteration.iteration}</td><td>{iteration.graphStates}</td><td>{iteration.graphEdges}</td><td>{iteration.occupiedStates}</td><td>{iteration.neighboursEnumerated}</td><td>{iteration.neighboursPriced}</td><td>{iteration.statesAdded}</td><td>{iteration.objective.toFixed(3)}</td><td>{iteration.bestOmittedIntervalGain.toFixed(3)}</td><td>{iteration.masterStateId}</td><td>{(iteration.elapsedMs / 1000).toFixed(2)} s</td></tr>)}</tbody></table></div></div></details>

    <details className="result-panel"><summary><span>Network-search and regularization audit</span><small>Exact mask-DP scores plus hard temporal lazy cuts</small></summary><div className="result-panel__body"><p className="method-note">{result.network.certificate}</p><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Reticulations</th><th>Networks scored</th><th>Temporal rejects</th><th>Beam retained</th><th>Best objective</th><th>Data parsimony</th><th>Overlap</th><th>Time</th></tr></thead><tbody>{result.network.search.map((step) => <tr key={step.reticulations}><td>{step.reticulations}</td><td>{step.candidatesScored}</td><td>{step.temporallyRejected}</td><td>{step.beamRetained}</td><td>{step.bestObjective.toFixed(3)}</td><td>{step.bestDataParsimony.toFixed(3)}</td><td>{step.bestOverlap}</td><td>{(step.elapsedMs / 1000).toFixed(2)} s</td></tr>)}</tbody></table></div><h3>Nondominated retained solutions</h3><div className="result-table-wrap"><table className="result-table"><thead><tr><th>Reticulations</th><th>Occurrences</th><th>Data parsimony</th><th>Penalized objective</th><th>Maximum overlap</th></tr></thead><tbody>{result.network.paretoFrontier.map((entry) => <tr key={`${entry.reticulations}-${entry.occurrences}`}><td>{entry.reticulations}</td><td>{entry.occurrences}</td><td>{entry.dataParsimony.toFixed(3)}</td><td>{entry.objective.toFixed(3)}</td><td>{entry.maximumOverlap}</td></tr>)}</tbody></table></div></div></details>
  </section>;
}
