import React, { useMemo, useRef } from "react";
import type { ScuffDiagnostic } from "@phylo-workbench/model-simulator/browser-source";
import { downloadSvg } from "../../lib/svg-export.js";

const COLORS = ["#167a70", "#d8644b", "#416eb5", "#b68128", "#7755c8", "#56a86c", "#d5538d", "#698a3d", "#b05d34", "#4f8eaa", "#8d6344", "#ca7e35", "#5463b9", "#36968e", "#9a5fa7", "#73816f", "#b84949", "#68a83a", "#4a76bd", "#d0933d"];

function linePath(values: readonly number[], width: number, height: number, minimum: number, maximum: number): string {
  return values.map((value, index) => `${index === 0 ? "M" : "L"}${42 + width * index / Math.max(1, values.length - 1)},${16 + height * (maximum - value) / Math.max(1e-12, maximum - minimum)}`).join(" ");
}

export function ScuffDiagnostics({ diagnostic }: { readonly diagnostic: ScuffDiagnostic }) {
  const fitnessRef = useRef<SVGSVGElement>(null);
  const frequencyRef = useRef<SVGSVGElement>(null);
  const dndsRef = useRef<SVGSVGElement>(null);
  const aminoAcids = useMemo(() => [...new Set(diagnostic.aminoAcids)].sort(), [diagnostic.aminoAcids]);
  const fitnessLines = aminoAcids.map((_, aa) => diagnostic.times.map((__, time) => diagnostic.fitness[time * 20 + aa]!));
  const fitnessMin = Math.min(...fitnessLines.flat());
  const fitnessMax = Math.max(...fitnessLines.flat());
  const aaFrequencies = aminoAcids.map((aminoAcid) => diagnostic.times.map((_, time) => {
    let total = 0;
    for (let codon = 0; codon < diagnostic.codons.length; codon += 1) if (diagnostic.aminoAcids[codon] === aminoAcid) total += diagnostic.codonFrequencies[time * diagnostic.codons.length + codon]!;
    return total;
  }));
  const dndsMax = Math.max(diagnostic.maximumExpectedDnds * 1.05, ...diagnostic.dnds) * 1.05;
  return <section className="sim-scuff-results"><div className="section-heading"><div><p className="eyebrow">SCUFF process diagnostics</p><h3>Dynamic fitness, codon occupancy, and expected selection</h3><p>These are deterministic frequency propagations conditional on one sampled OU fitness path; sequence simulation itself uses the exact joint Gillespie process.</p></div></div><div className="sim-scuff-grid">
    <article className="figure-card"><div className="figure-card__heading"><div><strong>Amino-acid scaled fitness</strong><span>Twenty OU trajectories; fitness jumps and substitutions share the configured time scale.</span></div><button type="button" className="button button--secondary" onClick={() => fitnessRef.current && downloadSvg(fitnessRef.current, "SCUFF amino-acid fitness trajectories")}>SVG</button></div><svg ref={fitnessRef} viewBox="0 0 620 250"><rect x="42" y="16" width="554" height="194" fill="#fbfcfb" stroke="#e0e5e1" />{fitnessLines.map((values, index) => <path key={aminoAcids[index]} d={linePath(values, 554, 194, fitnessMin, fitnessMax)} fill="none" stroke={COLORS[index % COLORS.length]} strokeWidth="1" strokeOpacity="0.82" />)}<text x="319" y="240" textAnchor="middle" fontSize="10">time</text><text transform="translate(12 113) rotate(-90)" textAnchor="middle" fontSize="10">scaled fitness</text><text x="44" y="13" fontSize="7">{fitnessMax.toFixed(2)}</text><text x="44" y="221" fontSize="7">{fitnessMin.toFixed(2)}</text></svg></article>
    <article className="figure-card"><div className="figure-card__heading"><div><strong>Expected amino-acid occupancy</strong><span>Codon probabilities propagated through each piecewise-constant HB generator and aggregated by amino acid.</span></div><button type="button" className="button button--secondary" onClick={() => frequencyRef.current && downloadSvg(frequencyRef.current, "SCUFF expected amino-acid occupancy")}>SVG</button></div><svg ref={frequencyRef} viewBox="0 0 620 250"><rect x="42" y="16" width="554" height="194" fill="#fbfcfb" stroke="#e0e5e1" />{(() => { const lower = new Array<number>(diagnostic.times.length).fill(0); return aaFrequencies.map((values, aa) => { const upper = values.map((value, index) => lower[index]! + value); const top = upper.map((value, index) => `${index === 0 ? "M" : "L"}${42 + 554 * index / Math.max(1, values.length - 1)},${210 - 194 * value}`).join(" "); const bottom = [...lower].reverse().map((value, reverseIndex) => { const index = lower.length - 1 - reverseIndex; return `L${42 + 554 * index / Math.max(1, values.length - 1)},${210 - 194 * value}`; }).join(" "); lower.splice(0, lower.length, ...upper); return <path key={aminoAcids[aa]} d={`${top} ${bottom} Z`} fill={COLORS[aa % COLORS.length]} fillOpacity="0.82"><title>{aminoAcids[aa]}</title></path>; }); })()}<text x="319" y="240" textAnchor="middle" fontSize="10">time</text><text transform="translate(12 113) rotate(-90)" textAnchor="middle" fontSize="10">expected frequency</text></svg></article>
    <article className="figure-card sim-scuff-dnds"><div className="figure-card__heading"><div><strong>Instantaneous expected dN/dS</strong><span>Ratio-of-sums expectation; dotted line is the SCUFF maximum-mean approximation.</span></div><button type="button" className="button button--secondary" onClick={() => dndsRef.current && downloadSvg(dndsRef.current, "SCUFF expected dN-dS")}>SVG</button></div><svg ref={dndsRef} viewBox="0 0 920 250"><rect x="48" y="16" width="848" height="194" fill="#fbfcfb" stroke="#e0e5e1" /><line x1="48" x2="896" y1={16 + 194 * (dndsMax - 1) / dndsMax} y2={16 + 194 * (dndsMax - 1) / dndsMax} stroke="#7d8985" strokeDasharray="4 4" /><line x1="48" x2="896" y1={16 + 194 * (dndsMax - diagnostic.maximumExpectedDnds) / dndsMax} y2={16 + 194 * (dndsMax - diagnostic.maximumExpectedDnds) / dndsMax} stroke="#d8644b" strokeDasharray="5 3" /><path d={linePath(diagnostic.dnds, 848, 194, 0, dndsMax)} fill="none" stroke="#167a70" strokeWidth="2.2" /><text x="472" y="240" textAnchor="middle" fontSize="10">time</text><text transform="translate(14 113) rotate(-90)" textAnchor="middle" fontSize="10">expected dN/dS</text><text x="890" y={12 + 194 * (dndsMax - diagnostic.maximumExpectedDnds) / dndsMax} textAnchor="end" fontSize="7" fill="#b54d3d">max-mean ≈ {diagnostic.maximumExpectedDnds.toFixed(3)}</text></svg><div className="sim-scuff-summary"><span>Trace mean <strong>{diagnostic.sampledMeanDnds.toFixed(3)}</strong></span><span>Approximate maximum mean <strong>{diagnostic.maximumExpectedDnds.toFixed(3)}</strong></span></div></article>
  </div></section>;
}
