import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import { extractSignals, megaTableCsv, type ComparisonRecord } from "../src/comparison.js";
import { writeComparisonPlots } from "../src/plots.js";

const fubar: ComparisonRecord = {
  id: "dataset:fubar:tree",
  dataset: "example.fasta",
  sourceId: "tree",
  sourceLabel: "FastTree",
  methodId: "fubar",
  methodLabel: "FUBAR",
  parameters: { posteriorThreshold: 0.95 },
  result: {
    sites: [
      { site: 1, pPositive: 0.99, pPurifying: 0.01, meanAlpha: 0.5, meanBeta: 2, selection: "positive" },
      { site: 2, pPositive: 0.2, pPurifying: 0.8, meanAlpha: 1, meanBeta: 0.5, selection: "none" },
    ],
  },
};

test("FUBAR comparison export contains reported and derived rate quantities", () => {
  const signals = extractSignals(fubar);
  assert.ok(signals.some((signal) => signal.metricId === "pPositive"));
  assert.ok(signals.some((signal) => signal.metricId === "posterior-mean-dn"));
  assert.ok(signals.some((signal) => signal.metricId === "posterior-mean-ds"));
  assert.ok(signals.some((signal) => signal.metricId === "log-mean-dn-minus-log-mean-ds"));
  assert.ok(signals.some((signal) => signal.metricId === "exp-log-mean-rate-ratio"));
  const csv = megaTableCsv(signals, "site");
  assert.match(csv, /Posterior mean dN/);
  assert.match(csv, /log\(E\[dN\]\) - log\(E\[dS\]\)/);
});

test("plot exporter writes native SVG FUBAR profiles", async () => {
  const directory = await mkdtemp(resolve(".evo-cli-plots-"));
  try {
    const plots = await writeComparisonPlots(directory, extractSignals(fubar));
    assert.ok(plots.some((plot) => plot.kind === "sites-by-results"));
    assert.ok(plots.some((plot) => plot.kind === "fubar-selection"));
    assert.ok(plots.some((plot) => plot.kind === "fubar-rates"));
    const svg = await readFile(plots[0]!.path, "utf8");
    assert.match(svg, /^<svg/);
    assert.match(svg, /Generated by evo-cli/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
