import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import { extractSignals, megaTableCsv, type ComparisonRecord } from "../src/comparison.js";
import { writeComparisonPlots } from "../src/plots.js";
import { replotPipeline } from "../src/replot.js";
import { writeStandardMethodTables } from "../src/standard-output.js";
import { applyVisualizationSettings, resolveVisualizationSettings } from "../src/visualization.js";

const fubar: ComparisonRecord = {
  id: "dataset:fubar:tree",
  dataset: "example.fasta",
  sourceId: "tree",
  sourceLabel: "FastTree",
  methodId: "fubar",
  methodLabel: "FUBAR",
  parameters: { posteriorThreshold: 0.95 },
  result: {
    sites: [
      { site: 1, pPositive: 0.99, pPurifying: 0.01, meanAlpha: 0.5, meanBeta: 2, selection: "positive" },
      { site: 2, pPositive: 0.2, pPurifying: 0.8, meanAlpha: 1, meanBeta: 0.5, selection: "none" },
    ],
    posterior: {
      siteCount: 2,
      gridSize: 2,
      gridValues: [0.5, 2],
      surfaces: [0.1, 0.2, 0.3, 0.4, 0.4, 0.3, 0.2, 0.1],
      alpha: [0.8, 0.2, 0.4, 0.6],
      beta: [0.1, 0.9, 0.7, 0.3],
    },
  },
};

test("FUBAR comparison export contains reported and derived rate quantities", () => {
  const signals = extractSignals(fubar);
  assert.ok(signals.some((signal) => signal.metricId === "pPositive"));
  assert.ok(signals.some((signal) => signal.metricId === "posterior-mean-dn"));
  assert.ok(signals.some((signal) => signal.metricId === "posterior-mean-ds"));
  assert.ok(signals.some((signal) => signal.metricId === "log-mean-dn-minus-log-mean-ds"));
  assert.ok(signals.some((signal) => signal.metricId === "exp-log-mean-rate-ratio"));
  const csv = megaTableCsv(signals, "site");
  assert.match(csv, /Posterior mean dN/);
  assert.match(csv, /log\(E\[dN\]\) - log\(E\[dS\]\)/);
});

test("plot exporter writes native SVG FUBAR profiles", async () => {
  const directory = await mkdtemp(resolve(".evo-cli-plots-"));
  try {
    const plots = await writeComparisonPlots(directory, extractSignals(fubar));
    assert.ok(plots.some((plot) => plot.kind === "sites-by-results"));
    assert.ok(plots.some((plot) => plot.kind === "fubar-selection"));
    assert.ok(plots.some((plot) => plot.kind === "fubar-rates"));
    const svg = await readFile(plots[0]!.path, "utf8");
    assert.match(svg, /^<svg/);
    assert.match(svg, /Generated by evo-cli/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("standard method table includes raw, derived, and threshold-dependent quantities", async () => {
  const directory = await mkdtemp(resolve(".evo-cli-standard-"));
  try {
    const settings = resolveVisualizationSettings(fubar, {
      methods: { fubar: { positivePosteriorThreshold: 0.995, purifyingPosteriorThreshold: 0.75 } },
    });
    const signals = applyVisualizationSettings(extractSignals(fubar), settings);
    const files = await writeStandardMethodTables(directory, fubar, signals, settings);
    assert.ok(files.some((file) => file.path.endsWith("results.csv")));
    const csv = await readFile(resolve(directory, "results.csv"), "utf8");
    assert.match(csv, /posterior-mean-dn/);
    assert.match(csv, /posterior-mean-ds/);
    assert.match(csv, /posterior-mean-log-rate-ratio/);
    assert.match(csv, /posterior-geometric-mean-rate-ratio/);
    assert.match(csv, /positive_selected_at_threshold/);
    assert.match(csv, /purifying_selected_at_threshold/);
    assert.match(csv, /0\.995/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("--replot regenerates outputs from saved result JSON without analyses", async () => {
  const output = await mkdtemp(resolve(".evo-cli-replot-output-"));
  const configDirectory = await mkdtemp(resolve(".evo-cli-replot-config-"));
  try {
    const nodes = [
      { id: "fast", kind: "fasttree", parameters: {} },
      { id: "fubar", kind: "model", modelId: "fubar", parameters: {} },
    ];
    const original = { schemaVersion: 1, id: "replot-test", name: "Replot test", nodes };
    const adjusted = {
      ...original,
      visualization: { methods: { fubar: { positivePosteriorThreshold: 0.995, purifyingPosteriorThreshold: 0.75, maxSitesPerPlot: 20 } } },
    };
    const analysisDirectory = resolve(output, "datasets", "001-example", "analyses", "fubar-via-fasttree");
    await mkdir(analysisDirectory, { recursive: true });
    await writeFile(resolve(output, "pipeline.json"), `${JSON.stringify(original)}\n`);
    await writeFile(resolve(configDirectory, "adjusted.json"), `${JSON.stringify(adjusted)}\n`);
    await writeFile(resolve(analysisDirectory, "result.json"), `${JSON.stringify(fubar.result)}\n`);
    await writeFile(resolve(output, "replot-index.json"), `${JSON.stringify({
      format: "evoonline-cli-replot-index",
      schemaVersion: 1,
      records: [{
        id: "001-example:fubar:fast",
        dataset: "example.fasta",
        datasetId: "001-example",
        nodeId: "fubar",
        sourceId: "fast",
        sourceNodeId: "fast",
        sourceLabel: "FastTree",
        methodId: "fubar",
        methodLabel: "FUBAR",
        parameters: {},
        resultPath: "datasets/001-example/analyses/fubar-via-fasttree/result.json",
        outputDirectory: "datasets/001-example/analyses/fubar-via-fasttree",
        simulationTruth: false,
      }],
    })}\n`);
    const summary = await replotPipeline({ configPath: resolve(configDirectory, "adjusted.json"), outputDirectory: output, quiet: true });
    assert.equal(summary.records, 1);
    const manifest = JSON.parse(await readFile(summary.manifestPath, "utf8")) as { readonly summary: { readonly analysisMethodsRerun: number } };
    assert.equal(manifest.summary.analysisMethodsRerun, 0);
    const csv = await readFile(resolve(analysisDirectory, "results.csv"), "utf8");
    assert.match(csv, /0\.995/);
    assert.match(csv, /false/);
    assert.ok((await readFile(resolve(analysisDirectory, "plots", "fubar-positive-violin.svg"), "utf8")).startsWith("<svg"));
    assert.ok((await readFile(resolve(output, "comparisons", "mega-table-sites.csv"), "utf8")).includes("Posterior mean dN"));
    await writeFile(resolve(configDirectory, "invalid-analysis-change.json"), `${JSON.stringify({ ...adjusted, execution: { maxCpus: 2 } })}\n`);
    await assert.rejects(
      () => replotPipeline({ configPath: resolve(configDirectory, "invalid-analysis-change.json"), outputDirectory: output, quiet: true }),
      /only accepts visualization changes/u,
    );
  } finally {
    await rm(output, { recursive: true, force: true });
    await rm(configDirectory, { recursive: true, force: true });
  }
});
