import type { PhyloWorkspaceSnapshot } from "@phylo-workbench/domain";
import {
  defaultsFromManifest,
  type AnalysisJobSpec,
  type ModelManifest,
  type ModelPlugin,
  type ModelValidation,
  type ValidationIssue,
} from "@phylo-workbench/model-sdk";
import { parseFsartFasta } from "./alignment.js";
import type { FsartAnalysisResult } from "./types.js";

export const fsartManifest: ModelManifest = {
  id: "fsart",
  version: "0.1.0",
  title: "Fast Stepwise Approximate Recombination Test",
  shortTitle: "FSART",
  description: "Aggregate pair-covered informative-triplet scans into consensus boundaries, fit a segment/pair/triplet tree family, and rapidly search its cached site likelihoods with a topology HMM.",
  category: "recombination",
  inputSlots: [{
    id: "alignment",
    label: "Nucleotide alignment",
    kind: "alignment",
    required: true,
    description: "Aligned nucleotide FASTA; codon frame is not required and ambiguity is ignored triplet-by-triplet.",
  }],
  parameters: [
    { id: "window", label: "Informative events per flank", description: "Each tested boundary compares this many informative pair-pattern events on either side.", type: "integer", default: 24, minimum: 8, maximum: 128, step: 2 },
    { id: "runFastTree", label: "Build the FastTree proposal family", description: "Fit a tree to every consensus segment, adjacent pair, adjacent triplet, and the whole alignment.", type: "boolean", default: true },
    { id: "runTreeHmm", label: "Search topology-mixture HMMs", description: "Recommended. Cache every retained topology's likelihood at every site, then use beam search plus add/drop/swap floating moves before an exact forward/backward fit.", type: "boolean", default: true },
    { id: "criterion", label: "Topology-set criterion", description: "Lower is better. AICc is the default penalty for the rapidly searched joint tree-HMM reconstruction.", type: "select", default: "aicc", options: [{ value: "aicc", label: "AICc (recommended)" }, { value: "aic", label: "AIC" }, { value: "bic", label: "BIC" }] },
    { id: "fastTreeFastest", label: "Use FastTree's fastest topology search", description: "Faster and appropriate for this screening analysis, but may lose topology accuracy on difficult alignments.", type: "boolean", default: true },
    { id: "minimumSegmentLength", label: "Minimum tree segment length", description: "Hard spacing between consensus boundaries and minimum Viterbi run length. EvoOnline also requires enough columns to expect max(30, 2 × taxa) variable sites at the alignment's observed diversity.", type: "integer", default: 150, minimum: 60, maximum: 10000, step: 1, advanced: true },
    { id: "mergeDistance", label: "Consensus kernel radius", description: "Local radius used to accumulate independent triplet count and strength around each breakpoint proposal.", type: "integer", default: 12, minimum: 0, maximum: 500, step: 1, advanced: true },
    { id: "maximumTriplets", label: "Supplemental triplet budget", description: "Large scans always include a deterministic all-pairs cover, then add alignment-wide triplets up to this budget. The pair cover is never truncated.", type: "integer", default: 250000, minimum: 100, maximum: 10000000, step: 1000, advanced: true },
    { id: "maximumSignals", label: "Retained scan signals", description: "Global bounded heap size for triplet peaks entering consensus construction.", type: "integer", default: 1024, minimum: 32, maximum: 10000, step: 32, advanced: true },
    { id: "maximumReportedSignals", label: "Triplet HMM refinements", description: "Bounded refinement budget; half remains reserved for spatially distinct peaks before consensus aggregation.", type: "integer", default: 256, minimum: 16, maximum: 4000, step: 16, advanced: true },
    { id: "rateSlices", label: "Switching-rate slices", description: "Coarse log-spaced HMM switching-rate values marginalized without Baum-Welch.", type: "integer", default: 9, minimum: 3, maximum: 25, step: 2, advanced: true },
    { id: "credibleMass", label: "Breakpoint interval mass", description: "Equal-tailed mass within the candidate-anchored local HMM switch mode; unrelated switch modes are excluded.", type: "number", default: 0.95, minimum: 0.5, maximum: 0.999, step: 0.01, advanced: true },
    { id: "maximumConsensusBreakpoints", label: "Consensus boundary limit", description: "Maximum hard-spaced boundaries used to generate the segment/pair/triplet tree family.", type: "integer", default: 14, minimum: 1, maximum: 30, step: 1, advanced: true },
    { id: "maximumTreeHypotheses", label: "Scored topology-family limit", description: "Safety cap after exact unrooted-topology deduplication. The default covers the full family generated by fourteen boundaries.", type: "integer", default: 48, minimum: 2, maximum: 64, step: 1, advanced: true },
    { id: "maximumHmmStates", label: "Maximum selected HMM states", description: "Maximum topology states in the rapid beam/floating subset search, after all family emissions have been cached.", type: "integer", default: 8, minimum: 1, maximum: 16, step: 1, advanced: true },
    { id: "treeHmmBeamWidth", label: "Topology-search beam width", description: "Number of competing subsets retained at each size before reversible add/drop/swap polishing.", type: "integer", default: 4, minimum: 1, maximum: 12, step: 1, advanced: true },
    { id: "treeHmmSourceWeight", label: "Tree-state source weight", description: "Relative column weight given to each topology's source segment while FastTree optimizes state-specific branch lengths. Four preserves regional branch-length signal without an expensive HMM/branch-length iteration.", type: "integer", default: 4, minimum: 1, maximum: 8, step: 1, advanced: true },
    { id: "treeHmmRateSlices", label: "Tree-HMM switch-rate slices", description: "Discrete expected-reset rates integrated by the O(L×trees) forward/backward algorithm.", type: "integer", default: 13, minimum: 5, maximum: 25, step: 2, advanced: true },
    { id: "refineTreeHmm", label: "Refine Viterbi boundaries and trees", description: "Recommended. Refit each selected topology on its assigned Viterbi runs, rescore all sites, and iterate while recording—but not requiring—convergence.", type: "boolean", default: true },
    { id: "maximumRefinementIterations", label: "Maximum refinement iterations", description: "Bounded Viterbi → tree refit → site-rescore cycles.", type: "integer", default: 3, minimum: 1, maximum: 8, step: 1, advanced: true },
    { id: "refinementBoundaryTolerance", label: "Boundary convergence tolerance", description: "Maximum aligned-site shift considered stable when the selected topology set is unchanged.", type: "integer", default: 3, minimum: 0, maximum: 30, step: 1, advanced: true },
  ],
  runtimes: ["browser-wasm"],
  outputKinds: ["breakpoint-table", "breakpoint-uncertainty", "triplet-topology-trace", "tree-family", "viterbi-partition", "segment-trees", "tree-hmm", "switch-posterior", "svg", "csv"],
  citation: "Informative-triplet scan inspired by RDP/RDP5 (Martin et al.); a CHMMera-inspired linear-time topology HMM searches cached FastTree site likelihoods under an information criterion. FSART remains an independent EvoOnline method, not exact RDP, BURT, or GARD software.",
};

export function validateFsartWorkspace(workspace: PhyloWorkspaceSnapshot): ModelValidation {
  const issues: ValidationIssue[] = [];
  if (workspace.alignment === undefined) issues.push({ severity: "error", code: "ALIGNMENT_REQUIRED", message: "Load an aligned nucleotide FASTA.", artifact: "alignment" });
  else {
    try {
      const parsed = parseFsartFasta(workspace.alignment.text);
      if (parsed.taxa < 4) issues.push({ severity: "warning", code: "LOW_TAXA", message: "Only one taxa triplet is available; breakpoint evidence cannot be corroborated across triplets.", artifact: "alignment" });
    } catch (error) {
      issues.push({ severity: "error", code: "INVALID_ALIGNMENT", message: error instanceof Error ? error.message : String(error), artifact: "alignment" });
    }
  }
  return { ready: !issues.some((issue) => issue.severity === "error"), issues };
}

export const fsartPlugin: ModelPlugin<FsartAnalysisResult> = {
  manifest: fsartManifest,
  validate: validateFsartWorkspace,
  defaultParameters: () => defaultsFromManifest(fsartManifest),
  createJob: (workspace, parameters): AnalysisJobSpec => ({
    schemaVersion: 1,
    model: { id: fsartManifest.id, version: fsartManifest.version },
    inputs: { alignmentSha256: workspace.alignment.sha256 },
    parameters,
    requestedRuntime: "browser-wasm",
  }),
  resultToCsv: (result) => result.breakpointCsv,
};
